// Headers for responses generated by the Worker. public/_headers only applies to static
// assets, so every Worker response sets its own security and cache headers here.
export const SECURITY_HEADERS = {
  "X-Content-Type-Options": "nosniff",
  "Referrer-Policy": "strict-origin-when-cross-origin",
  "Permissions-Policy": "camera=(), microphone=(), geolocation=(), payment=(), usb=()",
  "Strict-Transport-Security": "max-age=31536000",
  "Content-Security-Policy": "default-src 'none'; frame-ancestors 'none'",
  "X-Robots-Tag": "noindex",
  "Cache-Control": "no-store",
};

export function json(body, status = 200, extra = {}) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...SECURITY_HEADERS, "Content-Type": "application/json; charset=utf-8", ...extra },
  });
}

export function text(body, status = 200, extra = {}) {
  return new Response(body, { status, headers: { ...SECURITY_HEADERS, "Content-Type": "text/plain; charset=utf-8", ...extra } });
}

export function errorJson(status, error, retryAfterSeconds, extra = {}) {
  const body = retryAfterSeconds != null ? { error, retryAfterSeconds } : { error };
  const h = retryAfterSeconds != null ? { "Retry-After": String(retryAfterSeconds), ...extra } : extra;
  return json(body, status, h);
}

export const CORS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "GET, HEAD, OPTIONS",
  "Access-Control-Max-Age": "86400",
};
