// Writes docs/WORDLIST-DIFF.md: the old live list (word-list npm package, from the git tag
// live-before-upgrade) compared with ENABLE, including sample searches run through the
// same engine on both lists. Usage: node scripts/wordlist-diff.mjs
import fs from "node:fs";
import path from "node:path";
import { execFileSync } from "node:child_process";
import { createRequire } from "node:module";
import { loadEnable, blockedWords, fmt } from "./wordstats.mjs";

const ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, "$1")), "..");
const require = createRequire(import.meta.url);
const engineAt = () => { const p = require.resolve(path.join(ROOT, "src/assets/engine.js")); delete require.cache[p]; return require(p); };

const oldSrc = execFileSync("git", ["show", "live-before-upgrade:Letterpile/data/words.js"], { cwd: ROOT, encoding: "utf8", maxBuffer: 1 << 26 });
const OLD = oldSrc.slice(oldSrc.indexOf('WORD_DATA="') + 11, oldSrc.lastIndexOf('"')).split(" ");
const NEW = loadEnable().words;
const oldSet = new Set(OLD), newSet = new Set(NEW);
const onlyOld = OLD.filter(w => !newSet.has(w)).sort();
const onlyNew = NEW.filter(w => !oldSet.has(w));
const blocked = new Set(blockedWords(NEW));

const Eo = engineAt(); Eo.init(OLD);
const En = engineAt(); En.init(NEW);
const lenDist = list => { const d = {}; for (const w of list) d[w.length] = (d[w.length] || 0) + 1; return d; };
const dOld = lenDist(OLD), dNew = lenDist(NEW);
const maxLen = Math.max(...Object.keys(dOld).map(Number), ...Object.keys(dNew).map(Number));

// Evenly spaced, deterministic sample (no hand-picking, nothing from the blocklist shown).
const sample = (list, n) => { const ok = list.filter(w => !blocked.has(w)); return Array.from({ length: Math.min(n, ok.length) }, (_, i) => ok[Math.floor(i * ok.length / n)]); };

const searches = [
  ["Unscramble `retinas`", E => E.unscramble("retinas").length],
  ["Unscramble `listen`", E => E.unscramble("listen").length],
  ["Unscramble `aerostl?` (7 letters + 1 blank)", E => E.unscramble("aerostl?").length],
  ["Unscramble `tacre`, use every letter", E => E.unscramble("tacre", { exact: true }).length],
  ["Rack finder `retains` (tile scores)", E => E.findPlays("retains").length],
  ["Anagrams of `dormitory` (two-word)", E => E.anagrams("dormitory", { phrases: true, limit: 100000 }).phrases.length],
  ["Wordle: `crane` = gray, yellow, gray, gray, green", E => E.wordleCandidates([{ word: "crane", marks: "bybbg" }]).length],
  ["Wordle: no guesses (all five-letter words)", E => E.wordleCandidates([]).length],
  ["Crossword pattern `c?o?s`", E => E.patternSearch("c?o?s").length],
  ["Crossword pattern `????ing`", E => E.patternSearch("????ing").length],
];

const twoOld = OLD.filter(w => w.length === 2), twoNew = NEW.filter(w => w.length === 2);
const md = `# Word list change: old live list → ENABLE

Generated by \`node scripts/wordlist-diff.mjs\` (do not edit by hand). The old list is read from the git tag \`live-before-upgrade\` (\`data/words.js\`); ENABLE from \`data/enable1.txt\`. Both are run through the same \`engine.js\`, with nothing hidden (the counts below include words the new site hides by default; see the last section).

## Summary for Bee

- **Old list** (the \`word-list\` npm package, MIT, “derived from the Letterpress list”): **${fmt(OLD.length)}** words.
- **New list** (ENABLE, public domain): **${fmt(NEW.length)}** words.
- In both: **${fmt(NEW.length - onlyNew.length)}**. Only in the old list (these disappear from the site): **${fmt(onlyOld.length)}**. Only in ENABLE (these appear): **${fmt(onlyNew.length)}**, of which ${fmt(onlyNew.filter(w => blocked.has(w)).length)} are hidden by default as vulgar.
- Two-letter words: old **${twoOld.length}**, new **${twoNew.length}**. Words that were two-letter words and are gone: ${twoOld.filter(w => !newSet.has(w)).map(w => `\`${w}\``).join(", ")}. New two-letter words: ${twoNew.filter(w => !oldSet.has(w)).map(w => `\`${w}\``).join(", ") || "none"}.
- \`qi\`: old ${oldSet.has("qi") ? "yes" : "no"}, new ${newSet.has("qi") ? "yes" : "no"}. \`za\`: old ${oldSet.has("za") ? "yes" : "no"}, new ${newSet.has("za") ? "yes" : "no"}. \`zzz\`: old ${oldSet.has("zzz") ? "yes" : "no"}, new ${newSet.has("zzz") ? "yes" : "no"}. \`ok\`: old ${oldSet.has("ok") ? "yes" : "no"}, new ${newSet.has("ok") ? "yes" : "no"}. \`jo\`: old ${oldSet.has("jo") ? "yes" : "no"}, new ${newSet.has("jo") ? "yes" : "no"}.

### What this means for the Wordle Solver (plainly)

The old list had **${fmt(dOld[5])}** five-letter words; ENABLE has **${fmt(dNew[5])}**. The solver will now recognize and suggest **fewer** words. Neither list is Wordle's own answer or guess list, so the solver has always been able to suggest words the game would never use as an answer, and it can still miss words the game accepts. Returning visitors may notice that some words they used to see (for example British spellings and many obscure words) no longer appear.

## Sample searches (same engine, both lists)

| Search | Old list results | ENABLE results |
|---|---:|---:|
${searches.map(([name, fn]) => `| ${name} | ${fmt(fn(Eo))} | ${fmt(fn(En))} |`).join("\n")}

## Words per length

| Length | Old list | ENABLE |
|---:|---:|---:|
${Array.from({ length: maxLen }, (_, i) => i + 1).filter(n => dOld[n] || dNew[n]).map(n => `| ${n} | ${fmt(dOld[n] || 0)} | ${fmt(dNew[n] || 0)} |`).join("\n")}

## Samples

Evenly spaced samples, not hand-picked; words on the blocklist are left out of this document.

**Only in the old list (${fmt(onlyOld.length)}), 40 samples:** ${sample(onlyOld, 40).map(w => `\`${w}\``).join(", ")}

**Only in ENABLE (${fmt(onlyNew.length)}), up to 40 samples of the ones not hidden:** ${sample(onlyNew, 40).map(w => `\`${w}\``).join(", ")}

British spellings: ${fmt(onlyOld.filter(w => /ise$|ised$|ising$|isation$|our$/.test(w)).length)} of the old-only words end in -ise, -ised, -ising, -isation or -our (a rough indicator, not an exact count of British spellings).

## Words hidden by default

${fmt(blocked.size)} ENABLE words are hidden by default in the tools and never shown on static pages (\`data/blocklist*.txt\`, built by \`scripts/wordstats.mjs\`). The old list had already left most of these out: ${fmt([...blocked].filter(w => !oldSet.has(w)).length)} of the ${fmt(blocked.size)} were not in it.
`;
fs.mkdirSync(path.join(ROOT, "docs"), { recursive: true });
fs.writeFileSync(path.join(ROOT, "docs/WORDLIST-DIFF.md"), md);
console.log(md.split("## Words per length")[0]);
